use_frameworks!

target 'JMSearchBar_Example' do
  pod 'JMSearchBar', :path => '../'

  target 'JMSearchBar_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0'
  end
end
